In [1]:
import numpy as np

In [3]:
kanto=np.array([1,5,9])
kanto

array([1, 5, 9])

In [4]:
type(kanto)

numpy.ndarray

In [8]:
arr1=[1,2,3]
arr2=[10,11,12]
np.dot(arr1,arr2)

68

In [13]:
arr_1=np.array(arr1)
arr_2=np.array(arr2)
(arr_1*arr_2).sum()

68

In [16]:
#used for downloading the file directly from the source link
import urllib.request

urllib.request.urlretrieve(
'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv' ,
    'climate.txt'
)

('climate.txt', <http.client.HTTPMessage at 0xc96ab7bb88>)

In [17]:
climate_data=np.genfromtxt('climate.txt',delimiter=',',skip_header=1)
print(climate_data)

[[25. 76. 99.]
 [39. 65. 70.]
 [59. 45. 77.]
 ...
 [99. 62. 58.]
 [70. 71. 91.]
 [92. 39. 76.]]


In [19]:
climate_data.shape

(10000, 3)

In [35]:
weights=np.array([0.3,0.2,0.5])
yields=np.matmul(climate_data,weights)
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [22]:
yields.shape

(10000,)

In [29]:
#reshape krte waqat if you had dimension of 3,2 so you can do 2,3

test=yields
yields.reshape(10000,1)

array([[72.2],
       [59.7],
       [65.2],
       ...,
       [71.1],
       [80.7],
       [73.4]])

In [32]:
yields=test
print(yields)

[72.2 59.7 65.2 ... 71.1 80.7 73.4]


In [34]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None)
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    
    Returns
    -------
    res : ndarray
        The concatenated array.
    
    See Also
    --------
    ma.concatenate : Concatenate function that preserves input masks.
    array_split : Split an array into multiple sub-arrays of equal or
   

In [38]:
climate_result=np.concatenate((climate_data, yields.reshape(10000,1)), axis=1)
climate_result

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [40]:
np.savetxt('climate_result.txt',
          climate_result,
          fmt='%.2f',
          header='temperature,rainfall,humidity,yeilds')

In [11]:
arr4=np.array([
    [[11,12,13,14],
     [13,14,15,19]],
    
    [[15,16,17,21],
     [63,92,36,18]],
     
    [[98,32,81,23],
     [17,18,19.5,43]]])

In [12]:
arr4.shape

(3, 2, 4)

In [14]:
#single element
arr4[0,1,0]

13.0

In [17]:
#subarrays breakdown
arr4[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [18]:
#subarrays
arr4[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [22]:
arr4[1:,1, 3]

array([18., 43.])

In [ ]:
arr4[1:,1,3]

In [23]:
arr4=np.array([
    [[11,12,13,14],
     [13,14,15,19]],
    
    [[15,16,17,21],
     [63,92,36,18]],
     
    [[98,32,81,23],
     [17,18,19.5,43]]])

In [25]:
arr5=np.array([
    [[190,12,13,14],
     [13,14,15,19]],
    
    [[15,160,17,21],
     [63,92,36,18]],
     
    [[98,32,81,23],
     [17,18,19.5,43]]])

In [31]:
np.zeros(3)

array([0., 0., 0.])

In [33]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [34]:
np.eye(10) #identity matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
np.random.rand(3) #uniformly values are taken from 0-1 and 3 values are picked

array([0.14182423, 0.83537934, 0.18497764])

In [36]:
np.random.randn(2,3) #we generated the 2,3 matrix and the values are taken probablisticly

array([[-0.21467408, -0.58026898,  1.26984953],
       [-2.13165621, -0.53771811, -0.77220923]])

In [39]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, `None`, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array setting values 

In [40]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [41]:
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])